### ISSUE TITLE
Illegal argument: line must be positive: Error: Illegal argument: line must be positive

### ISSUE THREAD

**Issue by capaj** [jest-community/vscode-jest#156]
### Environment

1. `node -v`: 8.6.0
2. `npm -v`: 5.4.1
4. `npm ls react-scripts` (if you haven’t ejected): [fill]

1. Operating system: ubuntu 17.04

### Steps to Reproduce

opened up my project and saved a file

### Expected Behavior

no error is thrown

### Actual Behavior

error is thrown:
```

/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29 [Orta.vscode-jest] Illegal argument: line must be positive: Error: Illegal argument: line must be positive
	at Object.t.illegalArgument (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:56657)
	at new e (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:237724)
	at new e (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:240015)
	at diagnostics.set.asserts.map.assertion (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.4.2/out/src/diagnostics.js:19:48)
	at Array.map (native)
	at addTestsError (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.4.2/out/src/diagnostics.js:17:38)
	at testResults.forEach.result (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.4.2/out/src/diagnostics.js:32:21)
	at Array.forEach (native)
	at Object.updateDiagnostics (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.4.2/out/src/diagnostics.js:24:17)
	at JestExt.updateWithData (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.4.2/out/src/JestExt.js:307:23)
	at Runner.__dirname.startProcess.jestProcess.on.on (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.4.2/out/src/JestExt.js:61:18)
	at emitOne (events.js:96:13)
	at Runner.emit (events.js:191:7)
	at __dirname.default.start.debugprocess.stdout.on.data (/home/capaj/.vscode/extensions/Orta.vscode-jest-2.4.2/node_modules/jest-editor-support/build/Runner.js:67:18)
	at tryToString (fs.js:449:3)
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```
---

**Comment by connectdotz** [comment]
looks like either test result parsing has some problem or jest outputs something unexpected... however, regardless the cause, the extension probably better to report something (even though it might be "precise") than throwing an exception...

I will submit a PR to address the exception but will need more info to find out the actual root cause...

can you do a manual jest run (on shell) with the following options: `--json --useStderr --outputFile xxx` and send us the output file so maybe we can locate the root cause.
