### ISSUE TITLE
"Illegal argument: line must be positive" error thrown when testing an Angular service with missing provider

### ISSUE THREAD

**Issue by asgallant** [jest-community/vscode-jest#159]
### Environment

1. `node -v`: 8.6.0
2. `npm -v`: 5.3.0
4. `npm ls react-scripts` (if you haven’t ejected): n/a

1. Operating system: Windows 7

Jest version 21.2.1

### Steps to Reproduce

Create a service:
```typescript
import { Injectable } from '@angular/core';
@Injectable()
export class FooService {}
```
Write a test, missing a provider for FooService:
```typescript
import { inject, TestBed } from '@angular/core/testing';

import { FooService } from './foo.service';

describe('FooService', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [],
      providers: []
    });
  });

  it('should be created', inject([FooService], (service: FooService) => {
    expect(service).toBeTruthy();
  }));
});
```

### Expected Behavior

Test suite fails with error "No provider for FooService" (this is what the command-line Jest does).

### Actual Behavior

vscode-jest throws an exception:
```
[Orta.vscode-jest] Illegal argument: line must be positive: Error: Illegal argument: line must be positive
	at Object.t.illegalArgument (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:56657)
	at new e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:237802)
	at new e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:240093)
	at diagnostics.set.asserts.map.assertion (C:\Users\dgallant\.vscode\extensions\Orta.vscode-jest-2.4.2\out\src\diagnostics.js:20:48)
	at Array.map (native)
	at addTestsError (C:\Users\dgallant\.vscode\extensions\Orta.vscode-jest-2.4.2\out\src\diagnostics.js:18:38)
	at testResults.forEach.result (C:\Users\dgallant\.vscode\extensions\Orta.vscode-jest-2.4.2\out\src\diagnostics.js:33:21)
	at Array.forEach (native)
	at Object.updateDiagnostics (C:\Users\dgallant\.vscode\extensions\Orta.vscode-jest-2.4.2\out\src\diagnostics.js:25:17)
	at JestExt.updateWithData (C:\Users\dgallant\.vscode\extensions\Orta.vscode-jest-2.4.2\out\src\JestExt.js:307:23)
	at Runner.jestProcess.on.on (C:\Users\dgallant\.vscode\extensions\Orta.vscode-jest-2.4.2\out\src\JestExt.js:61:18)
	at emitOne (events.js:96:13)
	at Runner.emit (events.js:191:7)
	at C:\Users\dgallant\.vscode\extensions\Orta.vscode-jest-2.4.2\node_modules\jest-editor-support\build\Runner.js:67:18
	at tryToString (fs.js:449:3)
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```
and the Jest toolbar badge gets stuck on "Testing changes". 
![image](https://user-images.githubusercontent.com/5976786/32061169-f1bd62ac-ba3e-11e7-8ced-558680ad9888.png)

**Comment by bookman25** [comment]
What does your jest config look like?  Or can you create a sample repro in github that we can clone to try to reproduce?

**Comment by asgallant** [comment]
Here's the Jest config from my package.json:

```
"jest": {
  "collectCoverageFrom": [
    "src/**/*.{ts}",
    "!src/**/*.d.{ts}",
    "!src/**/*.types?.{ts}",
    "!src/environments**/*.{ts}",
    "!src/jestGlobalMocks.ts",
    "!src/main.ts",
    "!src/polyfills.ts",
    "!src/setupJest.ts",
    "!dist/**"
  ],
  "moduleNameMapper": {
    "app/(.*)": "<rootDir>/src/app/$1",
    "assets/(.*)": "<rootDir>/src/assets/$1",
    "environments/(.*?)(\\..*)": "<rootDir>/src/environments/$1.unit-test"
  },
  "preset": "jest-preset-angular",
  "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts"
}
```

The preset is https://github.com/thymikee/jest-preset-angular
