### ISSUE TITLE
vscode-jest stopping at launch of VSCode 

### ISSUE THREAD

**Issue by talentedjerkkk23** [jest-community/vscode-jest#360]
### Environment

1. `node -v`: v9.4.0 
1. `npm -v`: 6.3.0
1. VSCode: 1.25.1
1. Operating system: Windows 7 x64

### Prerequisite
- are you able to run jest test from command line? yes
- how do yo run your tests from command line? yarn test

###  Steps to Reproduce
1. Install Jest as dev-dependency
2. Create jest.config.js with following:
`module.exports = {
    verbose: true,
    testURL: "http://localhost/",
} `

### Expected Behavior
vscode-jest should work 

### Actual Behavior
After opening project with jest in VSCode:
 - vscode-jest stopped and printed the following: `Starting Jest in Watch mode failed too many times and has been stopped.`
- after reloading VSCode 100+ times - vscode-jest started working properly
- after another VSCode window reload vscode-jest stopped again

**Comment by Flavien-Pensato** [comment]
Did you try without `testURL` ?

**Comment by talentedjerkkk23** [comment]
@Flavien-Pensato yes, same thing

**Comment by connectdotz** [comment]
a few things to try:
1. do [self-diagnosis](https://github.com/jest-community/vscode-jest#plugin-not-running-as-expect-try-self-diagnosis): turning on the debug mode and see what command vscode-jest used to spaw your jest
1. if vscode-jest is not using `yarn test`, you can override it by setting the `jest.pathToJest`.

**Comment by talentedjerkkk23** [comment]
@connectdotz extension using `yarn jest` as i can see using debug mode.

**Comment by oleersoy** [comment]
I'm having the same problem.  

Jest is trying to scan the `node_modules` directory for tests even though I tell it to ignore it in `package.json`:

```
  "jest": {
    "testPathIgnorePatterns": [".test", "node_modules"]
  },

```
This is the console output:

```
jest-haste-map: @providesModule naming collision:
  Duplicate module name: prototype project
  Paths: /home/ole/SuperflyCSS/cli/test/sandbox/d5245d4c-b921-4e2a-9962-c82238ce0419/test/newproject/package.json collides with /home/ole/SuperflyCSS/cli/test/sandbox/7ab8e351-79e5-49c5-8f3c-ce0dd44d87c4/test/newproject/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.

internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ole/SuperflyCSS/cli/test/sandbox/7ab8e351-79e5-49c5-8f3c-ce0dd44d87c4/test/newproject/src'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1269:11)
    at NodeWatcher.watchdir (/home/ole/SuperflyCSS/cli/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/home/ole/SuperflyCSS/cli/node_modules/sane/src/common.js:116:12)
    at Walker.emit (events.js:182:13)
    at /home/ole/SuperflyCSS/cli/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/ole/SuperflyCSS/cli/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqCallback.oncomplete (fs.js:148:20)

internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ole/SuperflyCSS/cli/node_modules/unique-string'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1269:11)
    at NodeWatcher.watchdir (/home/ole/SuperflyCSS/cli/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/home/ole/SuperflyCSS/cli/node_modules/sane/src/common.js:116:12)
    at Walker.emit (events.js:182:13)
    at /home/ole/SuperflyCSS/cli/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/ole/SuperflyCSS/cli/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqCallback.oncomplete (fs.js:148:20)

internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ole/SuperflyCSS/cli/node_modules/unique-string'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1269:11)
    at NodeWatcher.watchdir (/home/ole/SuperflyCSS/cli/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/home/ole/SuperflyCSS/cli/node_modules/sane/src/common.js:116:12)
    at Walker.emit (events.js:182:13)
    at /home/ole/SuperflyCSS/cli/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/ole/SuperflyCSS/cli/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqCallback.oncomplete (fs.js:148:20)

internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ole/SuperflyCSS/cli/node_modules/unique-string'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1269:11)
    at NodeWatcher.watchdir (/home/ole/SuperflyCSS/cli/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/home/ole/SuperflyCSS/cli/node_modules/sane/src/common.js:116:12)
    at Walker.emit (events.js:182:13)
    at /home/ole/SuperflyCSS/cli/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/ole/SuperflyCSS/cli/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqCallback.oncomplete (fs.js:148:20)

internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/ole/SuperflyCSS/cli/node_modules/unique-string'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1269:11)
    at NodeWatcher.watchdir (/home/ole/SuperflyCSS/cli/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/home/ole/SuperflyCSS/cli/node_modules/sane/src/common.js:116:12)
    at Walker.emit (events.js:182:13)
    at /home/ole/SuperflyCSS/cli/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/ole/SuperflyCSS/cli/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqCallback.oncomplete (fs.js:148:20)

Starting Jest in Watch mode failed too many times and has been stopped.
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting


```

**Comment by jackdbd** [comment]
It looks the same issue described (and solved) [here](https://github.com/facebook/jest/issues/3254#issuecomment-297214395).

**Comment by Mahakb** [comment]
I also faced this issue. And the issue was with the name of my Project.

The Project Name should not have any space in it. Once, I changed the name of the project it worked perfectly for me.

**Comment by simlevesque** [comment]
If you see this, just know that it's most likely related to Jest watching every files inside your node_modules directory.

Add this to your jest config:
```
{
    "modulePathIgnorePatterns": [
      "node_modules"
    ]
  }
```

And then kill all node process currrently running `killall -9 node`.

It should fix the problem.
