### ISSUE TITLE
Test suite failed to run - Cannot find module

### ISSUE THREAD

**Issue by hnjoshi** [jest-community/vscode-jest#382]
### Environment

1. `node -v`: v8.11.3
1. `npm -v`: 5.6.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):
```
   $ npm ls jest
   /Users/hnjoshi/repos/control/content/private/react
   └── jest@23.3.0
```
1. your vscode-jest settings if customized:
```
  "jest.runAllTestsFirst": false,
  "jest.debugMode": true,
  "jest.pathToJest": "jest",
  "jest.pathToConfig": "/Users/hnjoshi/repos/my-app/content/private/react/package.json"
```

1. Operating system: [MacOS High Sierra, 10.13.6 (17G65)]

### Prerequisite
- are you able to run jest test from command line? [yes]
- how do yo run your tests from command line? `npm run test`

### Steps to Reproduce

rootDir/content/private/react/package.json - npm run test works fine from command line
```
  "scripts": {
    "test": "jest --no-cache",
    "test:coverage": "jest --coverage --no-cache",
    "test-watch": "jest --watch",
    "watch": "webpack --progress --watch"
  },
  "jest": {
    "cacheDirectory": "cache",
    "collectCoverageFrom": [
      "**/*.js",
      "!**/eslint-plugin-control/**",
      "!**/node_modules/**",
      "!**/coverage/**",
      "!webpack.config.js"
    ],
    "moduleNameMapper": {
      "^.+\\.(scss)$": "<rootDir>/__mocks__/styleMock.js"
    },
    "testRegex": "/__tests__/[^.].*js$",
    "setupFiles": [
      "<rootDir>/setup-jest.js",
      "<rootDir>/__mocks__/localStorageMock.js"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/setup-adapter.js",
    "snapshotSerializers": [
      "<rootDir>/node_modules/enzyme-to-json/serializer"
    ],
    "testEnvironment": "jest-environment-jsdom-global"
  }
```

rootDir/content/private/react/components/ - Test files are in this directory

### Relevant Debug Info

I think there is some issue with the `--include-path` but I could not tell what script is being executed when I save the test file. 

### Expected Behavior when test file is saved

Tests should pass or fail for all test suites related to changed files in the Output window.

### Actual Behavior

```
FAIL content/private/react/components/User/Details/__tests__/Details-test.js

  ● Test suite failed to run

    Cannot find module 'components/Name' from 'index.js'

      1 | import PropTypes from 'prop-types';
      2 | import React from 'react';
    > 3 | import Name from 'components/Name';
        | ^
      4 | import Input from 'components/Input';
      5 | import {
      6 |   Form,

      at Resolver.resolveModule (../../../../../../../usr/local/lib/node_modules/jest/node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (components/User/Details/index.js:3:1)


Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.542s
Ran all test suites related to changed files.
```

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by escaton** [comment]
Try to add this to jest config
```
"modulePaths": [
  "<rootDir>"
],
```

**Comment by hnjoshi** [comment]
@escaton Yes, it worked, thank you!!

**Comment by HassanNemir** [comment]
@escaton still doesn't work for me

**Comment by JBryant** [comment]
@escaton This worked for me! Thanks for saving me hours of more searching.

**Comment by RyanPWalker** [comment]
For me, it was a Git issue.  I had renamed the file locally but I guess git didn't register the change in filename.  I ran `mv name.js Name.js`, repushed, and then Jest was able to find it where I was building it from.

**Comment by hanchiang** [comment]
Good lord thanks @RyanPWalker for the insight! It turned out that this was my issue as well. I renamed a file, but somehow git didn't register it.
I just `git rm --cache <file>` and commit again.

**Comment by KarlWestgardh** [comment]
@RyanPWalker Thank you and @hanchiang as well for your solution to the problem, helped me out in my own project!

**Comment by keithlimmontajes** [comment]
where jest config on my package or on the node_modules jest config? thanks

**Comment by ignaciojvig** [comment]
I was having errors like the following:

**Cannot find module 'src/api/2 - services/services.module' from 'api/1 - controllers/wizard-controller/wizard.controller.spec.ts'**

And inside my package.json, in Jest config, I had the following property:
`...
"rootDir": "src"
`

So I think that my Jest was trying to search the modules starting with 'src' already inside 'src' folder (due to rootDir property)

I've just removed that property and it started working!

Also, the following property inside Jest config was also necessary:

`
...
"modulePaths": [
      "<rootDir>"
],
...
`

**Comment by mbougarne** [comment]
Sometimes if you're working with **Typescript** and you set the value of `"module"` in the `tsconfig.json` file to a different value than "commonjs", it may cause that issue.

**Comment by indraraj** [comment]
@ignaciojvig  I have some internal lib that I am accessing via moduleNameMapper like `"^@myLib/ui-services(.*)$": "<rootDir>/../services/src$1",` and this is working fine locally but on github action I am getting `error TS2307: Cannot find module '@myLib/ui-models/dist/js/ui.model' or its corresponding type declarations.`

**Comment by AHerod** [comment]
In my case the solution was installing **jsdom-global** package and creating a file **setup-jest.js**  with the following content:
`require('jsdom-global')();
`

**Comment by Nikolassantos** [comment]
This solution doesn't work for me !

**Comment by Anubha-jain** [comment]
> "modulePaths": [
>   "<rootDir>"
> ],

worked for me as well

**Comment by Anubha-jain** [comment]
> I was having errors like the following:
> 
> **Cannot find module 'src/api/2 - services/services.module' from 'api/1 - controllers/wizard-controller/wizard.controller.spec.ts'**
> 
> And inside my package.json, in Jest config, I had the following property: `... "rootDir": "src" `
> 
> So I think that my Jest was trying to search the modules starting with 'src' already inside 'src' folder (due to rootDir property)
> 
> I've just removed that property and it started working!
> 
> Also, the following property inside Jest config was also necessary:
> 
> `... "modulePaths": [ "<rootDir>" ], ...`

This worked for me as well.. Thanks

**Comment by rickyras** [comment]
> In my case the solution was installing **jsdom-global** package and creating a file **setup-jest.js** with the following content: `require('jsdom-global')(); `

This Worked for me . The required documents to follow can be found here:  [(https://www.npmjs.com/package/jsdom-global)]

**Comment by developius** [comment]
I ran into a similar problem where the name of a directory had a capital within it. On GitHub Actions, it raised an error when the case didn't match, but on my local machine (macOS), it ran just fine.

**Comment by novonimo** [comment]
with inspiring from @[escaton](https://github.com/escaton) answer, use 👍 

`
"modulePaths": [
  "<rootDir>/src"
],
`

**Comment by carolineccorrea** [comment]
delete node_modules work for me

**Comment by jalombro** [comment]
> Good lord thanks @RyanPWalker for the insight! It turned out that this was my issue as well. I renamed a file, but somehow git didn't register it. I just `git rm --cache <file>` and commit again.

this one saved me after  3 days of solving this error dayum. thanks a lot

**Comment by RxGoodness** [comment]
Add `"modulePaths": [ "<rootDir>/src" ],` to your jest.config

**Comment by ngrushet** [comment]
Guys, ran into this problem
I'm using Nest.  
My solution is to write these options: 
```
modulePaths": ["<rootDir>"],
"rootDir": ".",
```
in my package.json, in `jest` option. 
Result - command `npm run test` works and `npm run start:dev` also does

**Comment by TatianaMontoyaPrmnt** [comment]
> I ran into a similar problem where the name of a directory had a capital within it. On GitHub Actions, it raised an error when the case didn't match, but on my local machine (macOS), it ran just fine.

Hey! How did you solve this?

**Comment by profinvincible** [comment]
5 | test("renders learn react link", () => {
       6 |   render(<App />);
    >  7 |   const linkElement = screen.getByText(/learn react/i);
         |                              ^
       8 |   expect(linkElement).toBeInTheDocument();
       9 | });
      10 |

please i sincerely need help with this

**Comment by PetarKostadinovFT** [comment]
> **How I solved the problem:**
> 
> Since using absolute paths is a must for `ESModules` and I need to use `.js` extension at the end of the path:
> 
> ```ts
> export * from './helpers.js';
> ```
> 
> It broke the unit tests:
> 
> ```
>  - Test suite failed to run
> 
>     Cannot find module './helpers.js' from 'src/index.ts'
> ```
> 
> I updated Jest config with the following options and it fixed that:
> 
> ```
> moduleNameMapper: {
>     '^(\\.{1,2}/.*)\\.js$': '$1'
>   },
> ```
> 
> This regular expression `^(\\.{1,2}/.*)\\.js$` I found [here in the docs](https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/). Don't be afraid, it just matches any string that starts with one or two dots followed by a forward slash, followed by any number of characters, and ending with the ".js" file extension. All the following paths will be a match:
> 
> * `./app.js`
> * `../src/utils/helpers.js`
> * `../../lib/jquery.min.js`
> * `./../scripts/data.js`
> * etc
> 
> I hope it would help somebody!

this is great,
 works for me

**Comment by antrant** [comment]
> Good lord thanks @RyanPWalker for the insight! It turned out that this was my issue as well. I renamed a file, but somehow git didn't register it. I just `git rm --cache <file>` and commit again.

This works for me. TY!

**Comment by dezsoab** [comment]
> For me, it was a Git issue. I had renamed the file locally but I guess Git didn't register the change in filename. I ran `git mv name.js Name.js`, repushed, and then Jest was able to find it where I was building it from.

This did cost me 5hrs before finding your comment...... 👍  thank you 💯

**Comment by 6ygga** [comment]
I've added
        "modulePaths": [
            "<rootDir>"
        ],
 and changed
 "rootDir": "src",
 to
 "rootDir": "./",
 
 now everythins ok)

**Comment by TejaereleGo** [comment]
Im working with React js , now im getting this import issue when im trying to write the unit test cases using jest , 

```
 ● Test suite failed to run

    Cannot find module '@common/redux/formBuilder/selectors' from 'index.tsx'

    However, Jest was able to find:
        '../index.tsx'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      1 | import React, { useCallback, useEffect, useMemo, useState } from "react";
      2 | import { connect } from "react-redux";
    > 3 | import { getFieldsMapOfActiveFormSelector } from "@common/redux/formBuilder/selectors";
        | ^
      4 | import {
      5 |   FieldProps,
      6 |   FormFieldTypes,

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (app/presentation/FormBuilder/components/FormDropdownField/index.tsx:3:1)
      at Object.<anonymous> (app/presentation/FormBuilder/components/FormDropdownField/tests/FormDropdownField.test.tsx:61:1)

 FAIL  app/presentation/FormBuilder/components/FormDropdownField/tests/DropdownOptionSetup.test.tsx
  ● Test suite failed to run

    Cannot find module '@common/redux/formBuilder/selectors' from 'index.tsx'

    However, Jest was able to find:
        '../index.tsx'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      1 | import React, { useCallback, useEffect, useMemo, useState } from "react";
      2 | import { connect } from "react-redux";
    > 3 | import { getFieldsMapOfActiveFormSelector } from "@common/redux/formBuilder/selectors";
        | ^
      4 | import {
      5 |   FieldProps,
      6 |   FormFieldTypes,

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (app/presentation/FormBuilder/components/FormDropdownField/index.tsx:3:1)
      at Object.<anonymous> (app/presentation/FormBuilder/components/FormDropdownField/tests/DropdownOptionSetup.test.tsx:40:1)

```

and here the jest config file 
```

// jest.config.ts
import type { Config } from 'jest';
import { pathsToModuleNameMapper } from 'ts-jest';
import { compilerOptions } from './tsconfig.json';

const config: Config = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/app/' }),

  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  testMatch: ['**/?(*.)+(spec|test).(ts|tsx)'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],

};

export default config;
```

Help me in resolving this issue , basically im not understanding the root cause of the problem correctly.

**Comment by Vagner8** [comment]
Hello 
need to add the path to the 
like 
moduleNameMapper = {
      'your module name': '<rootDir>/node_modules/folder1/folder2/index file',
    }
