### ISSUE TITLE
Getting ReferenceError: Unknown option: .transform. Check out https://babeljs.io/docs/en/babel-core/#options when running command 'yarn test'

### ISSUE THREAD

**Issue by rahulguptacbre** [jest-community/vscode-jest#460]
I have installed Jest for my React Native app testing. But whenever I am trying to run my test cases, I am facing exception :

Test suite failed to run

    ReferenceError: Unknown option: .transform. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.

      at throwUnknownError (node_modules/@babel/core/lib/config/validation/options.js:124:11)
      at Object.keys.forEach.key (node_modules/@babel/core/lib/config/validation/options.js:108:5)
          at Array.forEach (<anonymous>)
      at validateNested (node_modules/@babel/core/lib/config/validation/options.js:84:21)
      at validate (node_modules/@babel/core/lib/config/validation/options.js:74:10)
      at file (node_modules/@babel/core/lib/config/config-chain.js:169:34)
      at cachedFunction (node_modules/@babel/core/lib/config/caching.js:33:19)
      at buildRootChain (node_modules/@babel/core/lib/config/config-chain.js:89:27)
      at loadPrivatePartialConfig (node_modules/@babel/core/lib/config/partial.js:85:55)
      at loadFullConfig (node_modules/@babel/core/lib/config/full.js:43:39)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.428s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Please help me for the same.

**Comment by connectdotz** [comment]
this extension expects a working jest environment, i.e. able to run jest test via command line in a terminal. If you are not able to run tests from the terminal, it's better to try react-native or babel community instead.
