### ISSUE TITLE
ENOENT: no such file or directory, access '<project dir>/node_modules/jest/bin/package.json'

### ISSUE THREAD

**Issue by mattdeboard** [jest-community/vscode-jest#497]
### Environment

1. `node -v`: v8.10.0
2. `npm -v`: 6.8.0
3. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@24.8.0
4. Operating system: OSX 10.14

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? `npm run test [test module] -- [--watch]`

### Steps to Reproduce

Working on Javascript project. I cannot reproduce the issue outside of my machine. But for me, I can reproduce by clicking the "Debug" code lens piece above a unit test. Doesn't matter what test module, as far as I can tell.

This functionality worked for months after switching to vscode earlier this year. But it seems after some update somewhere, something has gone askance.

### Relevant Debug Info

Here is a screenshot of the error:

![image](https://user-images.githubusercontent.com/306571/64357640-aa5bd800-cfca-11e9-82e7-26ae9dd83c20.png)

Here is a paste of the error message:

```
Exception has occurred: Error
Error: ENOENT: no such file or directory, access '/Users/mdeboard/truecar/consumer-frontend/node_modules/jest/bin/package.json'
    at Object.fs.accessSync (fs.js:322:11)
    at Function.module.exports.sync.fp [as sync] (/Users/mdeboard/truecar/consumer-frontend/node_modules/pkg-dir/node_modules/path-exists/index.js:12:6)
    at Function.module.exports.sync (/Users/mdeboard/truecar/consumer-frontend/node_modules/pkg-dir/node_modules/locate-path/index.js:20:18)
    at Function.module.exports.sync (/Users/mdeboard/truecar/consumer-frontend/node_modules/pkg-dir/node_modules/find-up/index.js:34:27)
    at Function.module.exports.sync.cwd [as sync] (/Users/mdeboard/truecar/consumer-frontend/node_modules/pkg-dir/index.js:8:20)
    at module.exports.filename (/Users/mdeboard/truecar/consumer-frontend/node_modules/import-local/index.js:7:27)
    at Object.<anonymous> (/Users/mdeboard/truecar/consumer-frontend/node_modules/jest/bin/jest.js:11:6)
    at Module._compile (module.js:646:14)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
```

### Expected Behavior

Test should run. Historically it has been great.

### Actual Behavior

An exception is thrown that it cannot find `node_modules/jest/bin/package.json`

**Comment by mattdeboard** [comment]
Ok I just figured this out. As per usual, PEBCAK.

I had checked, "All Exceptions" in the Jest test-runner UI. Unchecking that resolved it.

![image](https://user-images.githubusercontent.com/306571/64359464-fceac380-cfcd-11e9-99b3-bb109ab3fd52.png)

**Comment by strattonn** [comment]
I was trying to work out what was missing in package.json. Never would have thought to uncheck All Exceptions. Thanks!

**Comment by dandv** [comment]
This kind of error is cryptic AF and whatever causes it, should handle it. I ran into it in WebStorm, and if it weren't for Google and @mattdeboard's post, who knows how many hours I would've wasted tracking it down.

**Comment by pvinis** [comment]
So if there is a exception thrown that I do want to stop at, how do I do that then?
