### ISSUE TITLE
Jest encountered an unexpected token, ReactDOM.render(<App />, div);

### ISSUE THREAD

**Issue by PAAutofac** [jest-community/vscode-jest#517]
Hi team,

I have created a react app using "create react app" , installed Jest and trying to run jest and 
 I am experiencing following issue:
Could someone please advice , how to fix it.

$ ./node_modules/.bin/jest                                                                                               FAIL  src/App.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: C:\Test\counter-app\src\App.test.js: Unexpected token (7:18)

       5 | it('renders without crashing', () => {
       6 |   const div = document.createElement('div');
    >  7 |   ReactDOM.render(<App />, div);
         |                   ^
       8 |   ReactDOM.unmountComponentAtNode(div);
       9 | });
      10 |

      at Parser.raise (node_modules/@babel/parser/lib/index.js:6930:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:8323:16)
      at Parser.parseExprAtom (node_modules/@babel/parser/lib/index.js:9582:20)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:9165:23)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:9145:21)
      at Parser.parseExprOps (node_modules/@babel/parser/lib/index.js:9011:23)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/lib/index.js:8984:23)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/lib/index.js:8930:21)
      at Parser.parseExprListItem (node_modules/@babel/parser/lib/index.js:10252:18)
      at Parser.parseCallExpressionArguments (node_modules/@babel/parser/lib/index.js:9362:22)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.707s
Ran all test suites.

If you continue to experience problems please create a new issue and reference #125. I've locked the conversation for this issue since we've resolved the original and subsequent issues. 🔒

_Originally posted by @seanpoulter in https://github.com/jest-community/vscode-jest/issues/125#issuecomment-373598958_

**Comment by PAAutofac** [comment]
I fixed the issue myself.. as Jest already installed when we create react app using command "create-react-app" and to test the jest exists we need t give command npm test. we dont have to externally install the Jest library via npm.
