### ISSUE TITLE
Jest configuration issue: Cannot find module './test' from 'config/index.js'

### ISSUE THREAD

**Issue by JoshuaParkSJ** [jest-community/vscode-jest#614]
### Environment

1. `node -v`: 12.16.3
1. `npm -v`: 6.14.4
1. Operating system: Window 10 Enterprise Version 1809

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? npm run unit ("unit": "jest --verbose --runInBand" in package.json)

### Steps to Reproduce
npm run unit to reproduce bug

jest.config.js
```
module.exports = {
  testURL: 'http://localhost/',
  testResultsProcessor: 'jest-html-reporter',
  rootDir: './src',
  setupTestFrameworkScriptFile: '<rootDir>/test/setupJest.js',
  setupFiles: ['jest-localstorage-mock'],
  collectCoverage: true,
  coverageDirectory: '<rootDir>/../coverage',
  collectCoverageFrom: ['**/*.{js,jsx}'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': '<rootDir>/__mocks__/styleMock.js',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/__mocks__/fileMock.js',
  },
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/config/',
    'DebugController',
    '/coverage/',
    'index.js',
    'registerServiceWorker.js',
    '/server/',
    '/src/components/PageComponents/DebugPage/',
    '/__tests__/',
  ],
  testMatch: ['**/__tests__/**/*.js?(x)', '**/?(*.)(spec).js?(x)'],
  coverageReporters: ['lcov'],
};
```

src/components/navbar/__tests__/Navbar.test.js
```
import React from 'react';
import renderer from 'react-test-renderer';
import Navbar from '../Navbar';
import LanguageProvider from '../../contextProviders/LanguageProvider';
import ReduxProvider from '../../contextProviders/ReduxProvider';

describe('Navbar component', () => {
  it('matches the snapshot', () => {
    const tree = renderer
      .create(
        <ReduxProvider>
          <LanguageProvider>
            <Navbar filter> 
              <Navbar.Tab id="tabNavbar.inFlightOrders" component={null} />
              <Navbar.Tab id="tabNavbar.activeService" component={null} />
              <Navbar.Tab id="tabNavbar.activeService1" component={null} />
              <Navbar.Tab id="tabNavbar.activeService2" component={null} />
              <Navbar.Tab id="tabNavbar.activeService3" component={null} />
              <Navbar.Tab id="tabNavbar.activeService4" component={null} />
            </Navbar>
          </LanguageProvider>
        </ReduxProvider>
      )
      .toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```
src/config/index.js
```
const env = process.env.NODE_ENV || 'development';
const config = require(`./${env}`); // eslint-disable-line import/no-dynamic-require
config.env = env;
module.exports = config;
```
src/tests/setupJest.js
```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```

### Expected Behavior

Runs the tests in Navbar.test.js and test should be successful because it compares a snapshot of component to itself with no changes

### Actual Behavior

```
FAIL  src/components/navbar/__tests__/Navbar.test.js
  ● Test suite failed to run

    Cannot find module './test' from 'config/index.js'

    Require stack:
      config/index.js
      services/flowService.js
      store/slices/flowSlice.js
      store/reducers.js
      store/configureStore.js
      components/contextProviders/ReduxProvider.js
      components/navbar/__tests__/Navbar.test.js

      1 | const env = process.env.NODE_ENV || 'development';
    > 2 | const config = require(`./${env}`); // eslint-disable-line import/no-dynamic-require
        |                ^
      3 | config.env = env;
      4 | module.exports = config;
      5 | 

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:307:11)
      at Object.<anonymous> (config/index.js:2:16)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        11.819 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portal-starter-template-ui@1.0.1 unit: `jest --verbose --runInBand`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portal-starter-template-ui@1.0.1 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Madhavivb** [comment]
I am facing same issue , what is the resolution for this , comment pls? @JoshParkSJ

**Comment by Madhavivb** [comment]
@JoshParkSJ  could you pls help on how this was resolved ?
