### ISSUE TITLE
Failed to obtain test file list

### ISSUE THREAD

**Issue by bodote** [jest-community/vscode-jest#699]
### Environment

1. `vscode-jest version`: 4.0.1
2. `node -v`:v16.1.0
3. `npm -v` or `yarn --version`: 7.11.2 , Angular CLI: 12.0.0
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):
angular-jest-tutorial@0.0.0 /Users/bodo.teichmann/dev/learning/angular-jest-tutorial
```
├─┬ @angular-builders/jest@11.2.0
│ ├─┬ jest-preset-angular@8.4.0
│ │ ├── jest@26.6.3 deduped
│ │ └─┬ ts-jest@26.5.6
│ │   └── jest@26.6.3 deduped
│ └── jest@26.6.3 deduped
└── jest@26.6.3
```

5. your vscode-jest settings if customized:
    - jest.jestCommandLine? none/default
    - jest.autoRun? 

```
"jest.autoRun": "off"
```

6. Operating system: MacOS 11.3.1 (M1)

### Prerequisite
- are you able to run jest test from the command line? YES
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) 
`ng test`  or `jest` works both

### Steps to Reproduce
unfortunately only happens in a closed source mono-repo with 310 .spec.ts files, which I can not make publicly available.

### Relevant Debug Info
vscode - Console: ("toggle developer tools") : 
shows: 
```
electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
Module.require @ internal/modules/cjs/loader.js:1006
require @ internal/modules/cjs/helpers.js:88
t @ loader.js:1025
r._init @ loader.js:737
r.load @ loader.js:812
r.load @ loader.js:610
l @ loader.js:1631
r._loadModule @ loader.js:1643
r._resolve @ loader.js:1728
r.defineModule @ loader.js:1375
i @ loader.js:1847
E @ bootstrap-window.js:179
async function (async)
E @ bootstrap-window.js:57
(anonymous) @ workbench.js:21
(anonymous) @ workbench.js:216
console.ts:137 [Extension Host] (node:50910) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
_logExtensionHostMessage @ localProcessExtensionHost.ts:514
(anonymous) @ localProcessExtensionHost.ts:282
emit @ events.js:315
emit @ internal/child_process.js:903
processTicksAndRejections @ internal/process/task_queues.js:81
console.ts:137 [Extension Host] [frontend/JestProcessManager] starting process: {extContext: {…}, request: {…}, _id: "id: 0, request: {"type":"all-tests","listener":"ob…locking","dedup":{"filterByStatus":["pending"]}}}"}
console.ts:137 [Extension Host] [frontend/RunTestListener] all-tests onProcessStarting
console.ts:137 [Extension Host] spawning process with command=ng test --  --testLocationInResults --json --useStderr --outputFile /var/folders/3z/5hsmh7s91nx4rcdk9f29f0smgwp36k/T/jest_runner_frontend.json --no-coverage --no-color --reporters default --reporters "/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/reporter.js"
console.ts:137 [Extension Host] [frontend/JestProcessManager] starting process: {extContext: {…}, request: {…}, _id: "id: 2, request: {"type":"not-test","args":["--list…locking","dedup":{"filterByStatus":["pending"]}}}"}
console.ts:137 [Extension Host] [frontend/ListTestFileListener] not-test onProcessStarting
console.ts:137 [Extension Host] spawning process with command=ng test --  --listTests --json
console.ts:137 [Extension Host] [angular-jest-tutorial/JestProcessManager] starting process: {extContext: {…}, request: {…}, _id: "id: 3, request: {"type":"not-test","args":["--list…locking","dedup":{"filterByStatus":["pending"]}}}"}
console.ts:137 [Extension Host] [angular-jest-tutorial/ListTestFileListener] not-test onProcessStarting
console.ts:137 [Extension Host] spawning process with command="/Users/its_me/dev/learning/angular-jest-tutorial/node_modules/.bin/jest" --listTests --json
console.ts:137 [Extension Host] [angular-jest-tutorial/JestProcessManager] process ended: {extContext: {…}, request: {…}, _id: "id: 3, request: {"type":"not-test","args":["--list…locking","dedup":{"filterByStatus":["pending"]}}}", _stopReason: "process-end"}
console.ts:137 [Extension Host] [angular-jest-tutorial/ListTestFileListener] got 1 test files
console.ts:137 [Extension Host] [angular-jest-tutorial/JestExt] found 1 testFiles
console.ts:137 [Extension Host] [frontend/ListTestFileListener] failed to parse result: ["/Users/its_me/dev/workspace1/myproject/frontend/src/app/common/services/notification.socket.service.spec.ts","/Users/its_me/dev/workspace1/myproject/frontend/src/app/dirty-declaration/form-content/form-content.component.spec.ts","/Users/its_me/dev/workspace1/myproject/frontend/src/app/dirty-declaration/dirty-declaration.component.spec.ts","/Users/its_me/dev/workspace1/myproject/frontend/src/app/dirty-declaration/form-content/form-content.service.spec.ts",<.. about 310 .spec.ts files in total ..>,"/Users/its_me/dev/workspace1/myproject/frontend/src/app/user/+state/user.selector.spec.ts","/Users/its_me/dev/workspace1/myproject/frontend/src/app/common/services/action.service.sp error= Error: unexpected result
	at t.ListTestFileListener.onProcessClose (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1301610)
	at t.ListTestFileListener.onEvent (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1300018)
	at p.eventHandler (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1309916)
	at h.<anonymous> (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1310005)
	at h.emit (events.js:315:20)
	at ChildProcess.<anonymous> (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:806499)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] [frontend/JestExt] found undefined testFiles
console.ts:137 [Extension Host] [frontend/JestExt] (frontend) Failed to obtain test file list, something might not be setup right? Error: unexpected result
	at t.ListTestFileListener.onProcessClose (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1301610)
	at t.ListTestFileListener.onEvent (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1300018)
	at p.eventHandler (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1309916)
	at h.<anonymous> (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:1310005)
	at h.emit (events.js:315:20)
	at ChildProcess.<anonymous> (/Users/its_me/.vscode/extensions/orta.vscode-jest-4.0.1/out/extension.js:2:806499)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] [frontend/JestProcessManager] process ended: {extContext: {…}, request: {…}, _id: "id: 2, request: {"type":"not-test","args":["--list…locking","dedup":{"filterByStatus":["pending"]}}}", _stopReason: "process-end"}
``` 

### Expected Behavior

on initial opening the workspace and on every "Developer: Reload Window" the warning box " Failed to obtain test file list is shown

### Actual Behavior

on initial opening the workspace and on every "Developer: Reload Window" the warning box " no warning is shown

**Comment by connectdotz** [comment]
does it happen only the first time the workspace is opened? Did the extension work afterward or the runner just stop? can you post the output of the following command:
`ng test --listTests`

**Comment by connectdotz** [comment]
@bodote I was looking into this problem and saw the test file list output above contains "<.. about 310 .spec.ts files in total ..>", wondering if it is a console logging abbreviation or this is part of the actual output? We parse the output file with regex, which does not anticipate such non-file name message within, can you verify the actual output from your terminal with `ng test --listTests`?

**Comment by bodote** [comment]
"<.. about 310 .spec.ts files in total ..>" was introduced by myself by hand, since I can not disclose the real filenames from the project

**Comment by bodote** [comment]
`ng test --listTests` would give me the all *.spec.ts files, but also has a error message at the end that says:
Validation Error:

```
  Module <rootDir>/setup-jest.ts in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/bodo.teichmann/dev/workspace1/proj1/frontend/projects

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

**Comment by bodote** [comment]
>does it happen only the first time the workspace is opened? Did the extension work afterward or the runner just stop? 
no , the extension never works as expected

**Comment by bodote** [comment]
adding an additional <projRootDir>/projects/setup-jest.ts with contents:
```
import '../setup-jest';
```
fixed the problem.
Thank you for your help!

**Comment by connectdotz** [comment]
refering back from [comment](https://github.com/jest-community/vscode-jest/issues/697#issuecomment-855798746)

@bodote can you post `ng test --listTests --json` output

**Comment by bodote** [comment]
> can you post ng test --listTests --json output
here you go: 
[jest.list.out.log](https://github.com/jest-community/vscode-jest/files/6610294/jest.list.out.log)

**Comment by connectdotz** [comment]
interesting... jest reported 3 lists instead of 1, that is why the parse failed... ok, great, now we know the cause, fix is easy... stay tune.

**Comment by connectdotz** [comment]
However this issue should not stop the editor from showing test result in rc2 ... did you see the test results status indicators?

**Comment by bodote** [comment]
yeah, I do see the status indicators, but sometimes I got one or two out of several hundreds of tests indicate a "fail" but the tests do not show up in the "Problems" tab, which it should. but maybe this is not related to this bug here?
