### ISSUE TITLE
Jest unable to close due to openHandles

### ISSUE THREAD

**Issue by gjvengelen** [jest-community/vscode-jest#717]
### Environment

1. `vscode-jest version`: [fill]
2. `node -v`: v14.15.4
3. `npm -v`: 6.14.10
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): `-- (empty)
5. Operating system: Windows

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npx jest ./e2e --detectOpenHandles

### Steps to Reproduce
```
const puppeteer = require("puppeteer");
const { spawn } = require("child_process")
const waitForLocalhost = require("wait-for-localhost");

describe("productOverview", () => {
  let browser;
  let page;
  let frontendProcess;
  let backendProcess;
  beforeAll(async () => {
    console.log("starting application...");
    frontendProcess = spawn('npm', ["run start --prefix frontend"], { shell: true });
    backendProcess = spawn('npm', ["run start --prefix backend"], { shell: true });
    await waitForLocalhost({ port: 3000 });
    console.log("Application started");
  });
  beforeEach(async () => {
    //arrange
    browser = await puppeteer.launch({ headless: false });
    page = await browser.newPage();
    await page.goto("http://localhost:3000/");
  });
  afterEach(async () => {
    if(browser){
    await browser.close();
    }
  });
  afterAll(() => {
    if (frontendProcess) {
      console.log("Stopping application...");
      frontendProcess.kill('SIGTERM', {forceKillAfterTimeout: 1000});
      backendProcess.kill('SIGTERM', {forceKillAfterTimeout: 500});
      console.log("Application stopped");
    }
  });

  it("should show a product overview on navigation", async () => {
    //arrange
    //act
    //assert
    expect(await page.waitForSelector("#productTable")).not.toBeNull();
    expect(await page.waitForSelector("#productSearch")).not.toBeNull();
  });
  it("should redirect to the productDetails on click", async () => {
    //arrange
    //act
    await page.click("#product09 > a");
    //assert
    const url = await page.url();
    expect(url).toBe("http://localhost:3000/products/09");
  });
});
```
When running this code Jest is unable to finish the test due to openhandles. 

### Expected Behavior
1. Start react-scripts
2. Start backend server(express())
3. Run tests
4. Pass
5. Close FE and BE

### Actual Behavior

The tests pass(as expected) but jest does not finish:
```
 ●  PIPEWRAP

      10 |   beforeAll(async () => {
      11 |     console.log("starting application...");
      14 |     await waitForLocalhost({ port: 3000 });

          at Array.reduce (<anonymous>)
      at e2etest/productsOverview.e2e.spec.js:12:23


  ●  PIPEWRAP

      11 |     console.log("starting application...");
    > 13 |     backendProcess = spawn('npm', ["run start --prefix backend"], { shell: true });
      14 |     await waitForLocalhost({ port: 3000 });
      15 |     console.log("Application started");
      16 |   });
          at Array.reduce (<anonymous>)
      at e2etest/productsOverview.e2e.spec.js:13:22


  ●  DNSCHANNEL

      12 |     frontendProcess = spawn('npm', ["run start --prefix frontend"], { shell: true });
      13 |     backendProcess = spawn('npm', ["run start --prefix backend"], { shell: true });
    > 14 |     await waitForLocalhost({ port: 3000 });
         |           ^
      15 |     console.log("Application started");
      16 |   });
      17 |   beforeEach(async () => {

      at main (node_modules/wait-for-localhost/index.js:13:25)
      at node_modules/wait-for-localhost/index.js:25:3
      at waitForLocalhost (node_modules/wait-for-localhost/index.js:7:9)
      at e2etest/productsOverview.e2e.spec.js:14:11
```

**Comment by connectdotz** [comment]
do you see the same behavior when running jest via the command line?

**Comment by shrikky** [comment]
I also have this problem. Yes it is clean if I just use default cmdline jest.
