### ISSUE TITLE
Having trouble running manually (but auto-run works) in project using jest projects

### ISSUE THREAD

**Issue by tsgautier** [jest-community/vscode-jest#748]
### Environment

1. `vscode-jest version`: [v4.0.3]
2. `node -v`: [v12.22.4]
3. `npm -v` or `yarn --version`: [6.14.4]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [── jest@26.6.3]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: [MacOS 10.15.7]

### Prerequisite
- are you able to run jest test from the command line? [yes]
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [npx test]

### Steps to Reproduce

I had a working jest setup with vscode integrated well that would auto-run tests, run test on demand in the explorer.  
All of the configuration was combined into one setup, and I ran this using `$ npx jest test/unit` or `npx test test/integration`

This all worked on the command line and vscode.

Then I changed this setup so that it uses jest projects.  My root jest config in package.json looks like this:

```
  "jest": {
    "projects": [
      "<rootDir>/test/*"
    ]
  }

Where there are two directories, test/integration and test/unit which each contain their own individual jest.config.js.

```
On the command line, it still works properly.  In vscode, any auto-run test works properly.  But when I manually click run, or click run from the explorer, the command fails.  It appears to be a typescript compilation problem, as babel is complaining about syntax:

```
footer.test.ts: Missing semicolon. (4:13)

      2 |
      3 | test("render", () => {
    > 4 |     let props: Props = {
        |              ^
      5 |         links: [
      6 |             {
      7 |                 name: 'link one',

      at Parser._raise (node_modules/@babel/parser/src/parser/error.js:134:45)
      at Parser.raiseWithData (node_modules/@babel/parser/src/parser/error.js:129:17)
      at Parser.raise (node_modules/@babel/parser/src/parser/error.js:78:17)
      at Parser.semicolon (node_modules/@babel/parser/src/parser/util.js:137:10)
```

However, if I try to debug this the debugger launches the test and succeeds (presumably same reason the auto-run works?)

### Relevant Debug Info

[fill]

### Expected Behavior

[test passes when clicking "Run" in source or test explorer]

### Actual Behavior

[test fails with error above]

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by tsgautier** [comment]
I believe this is an issue with the Jest Test Explorer extension not this extension - closing.
