### ISSUE TITLE
Tests load infinitely in multi-project workspace

### ISSUE THREAD

**Issue by ckifer** [jest-community/vscode-jest#832]
### Environment

1. `vscode-jest version`: v4.2.1
2. `node -v`: v16.13.1
3. `npm -v` or `yarn --version`: npm v8.1.2
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): react-scripts@4.0.3/jest@26.6.0
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? default
    - jest.autoRun?  {"watch": true}
6. Operating system: OSX Big Sur 11.6.2 

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce

* load project in a workspace with multiple projects
* wait for tests to finish but they never do

### Relevant Debug Info

The output for the 3 projects in the workspace is in a continuous 'running' state that never stops. In each individual package, even with debug mode on I only get the following output:
```bash
not-test-43 is scheduled
Jest Session Started
```

This is the error produced in the VSCode devtools:
```bash
 [{packageName}/JestProcessManager] non-blocking-queue: process failed: Object RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 1
	at Object.getSystemErrorName (util.js:231:11)
	at errnoException (internal/errors.js:501:21)
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at spawn (child_process.js:570:9)
	at d.t.createProcess [as _createProcess] (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:816810)
	at d.value (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:821666)
	at p.startRunner (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1048005)
	at p.start (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1045833)
	at t.JestProcessManager.<anonymous> (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1049914)
	at Generator.next (<anonymous>)
	at /Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1048811
	at new Promise (<anonymous>)
	at r (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1048556)
	at t.JestProcessManager.run (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1049768)
	at t.JestProcessManager.scheduleJestProcess (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1049745)
	at Object.o [as scheduleProcess] (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1042950)
	at t.JestExt.updateTestFileList (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1032525)
	at t.JestExt.<anonymous> (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1027296)
	at Generator.next (<anonymous>)
	at a (/Users/ckifer/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2:1022383)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Expected Behavior

Tests should complete in a few seconds (very few test in the packages) and indicate success/failure/etc.

### Actual Behavior

Infinite loading with no indications of what might be going on other than the VSCode error. 

Things I have tried:
* Stopping/starting runners
* Uninstalling/reinstalling the extension
* Using the Jest setup command
* Turning auto run off and starting tests individually

Thanks!

**edit:** I found this thread https://github.com/microsoft/vscode/issues/138036 which I assume is the reason this isn't working at this point. Something in child_process hard crashing VS code.

**Comment by connectdotz** [comment]
this is interesting... we did spawn child process to run jest, but have never seen this kind of error... do you have a sample repo we can investigate further?

**Comment by ckifer** [comment]
@connectdotz currently don't have a repo that I can share but I will attempt create one and update here if I can reproduce the issue. If not it may be something on my side that isn't effecting anyone else. Thanks!

**Comment by ckifer** [comment]
@connectdotz here is a sample repo with multiple projects. Here I just made two CRA's with the TS template, added them to the same WS in VS Code and attempted to run Jest VS code with the same error and same results. Not sure it will be replicable on another machine but worth a shot.

https://github.com/ckifer/issue-832-jest-vscode

**Comment by connectdotz** [comment]
@ckifer thanks for the repo. I tried it but could not reproduce your issue. It worked perfectly for me. The problem is probably related to your specific env...

anyway, I did a quick search, found [this](https://stackoverflow.com/questions/57995646/error-err-out-of-range-when-using-npm-install):
```
The issue is a mismatch between your versions of Node and NPM. This can occur when one is updated without the other.
```

not sure if it applies to your situation.

**Comment by ckifer** [comment]
@connectdotz thanks for checking it out. Glad it isn't effecting everyone, I will probably do a fresh install of VS Code and extensions and see if I can get anywhere.

I'm using nvm to manage node/npm versions so they definitely aren't mismatching, might be something similar though. Either way I'll post back here if I find a solution.

**Comment by ckifer** [comment]
@connectdotz I am silly, sorry I couldn't figure this out on my own. I had jest.rootPath set to something totally different than the workspaces I was working in. I must've set it when jest wasn't picking up on my root and then forgotten about it. Thanks for the help, closing this.
