### ISSUE TITLE
Jest extension stopped working upon vscode update.

### ISSUE THREAD

**Issue by ANTGOMEZ** [jest-community/vscode-jest#996]
Issue Type: <b>Bug</b>

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

Yesterday I updated vscode to version above. Since then the Jest test extension stopped working. Test explorer is empty, no message displayed, just an empty test explorer panel. It was fine prior to vscode update.

I uninstalled Jest and installed it again and it stared working again.

It's fine now, but just wanted to report it in case it's an issue.

Extension version: 4.6.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by embetten** [comment]
+1 
Uninstalling and reinstalling does not resolve the issue for me. Jest Cli and jest debug configuration files are working, but the vscode extension's autowatch and test explorer are not working.

**Comment by connectdotz** [comment]
Noticed the vscode version 1.66 is pretty old (March 2022). The minimal vscode version for the current extension (5.x) is 1.68.1 (May 2022)... could you upgrade to that version or up?

**Comment by ANTGOMEZ** [comment]
That's strange, I got the update prompt, I clicked YES. It quit and came back. At that point, I assumed it had updated to the latest. I don't check version numbers, but I would assume an update does what it says.

**Comment by connectdotz** [comment]
@ANTGOMEZ  and @embetten, please let me know your current `vscode` and `vscode-jest` versions, You should be running `vscode-jest` 5.1+ and `vscode` 1.74+...

**Comment by embetten** [comment]
> @ANTGOMEZ and @embetten, please let me know your current `vscode` and `vscode-jest` versions, You should be running `vscode-jest` 5.1+ and `vscode` 1.74+...

I can confirm that I am running vscode-jest 5.2.2 and vscode version 1.74.3. 

consistently fails with "ERROR: Invalid Option: --testLocationInResults"

**Comment by xtina** [comment]
Workaround: downgrading to 4.6.0 has fixed this for me.

**Comment by embetten** [comment]
> Workaround: downgrading to 4.6.0 has fixed this for me.

+1

**Comment by connectdotz** [comment]
Sorry about that. Appreciate it if you can help us diagnose this issue.

Are you guys all on windows? in 5.2.2, can you show us the auto-config and the command line from the output terminal or console log? If you have customized anything related, please also mention it.

**Comment by JoshuaVSherman** [comment]
i'm on ubuntu vscode version 1.74.3 and it is no longer working
I upgraded jest to latest version and uninstalled/reinstalled your extension, still not working, also ran teh setup tool and played around with config, no luck
``[error] failed to retrieve test file list. TestExplorer might show incomplete test items``

**Comment by ANTGOMEZ** [comment]
> > @ANTGOMEZ and @embetten, please let me know your current `vscode` and `vscode-jest` versions, You should be running `vscode-jest` 5.1+ and `vscode` 1.74+...
> 
> I can confirm that I am running vscode-jest 5.2.2 and vscode version 1.74.3.
> 
> consistently fails with "ERROR: Invalid Option: --testLocationInResults" and the test explorer pannel is unable to list any tests.

I uninstalled VSCODE and reinstalled: 1.74.3
Then I uninstalled and reinstalled Jest: 5.2.2

Things are working now.

**Comment by connectdotz** [comment]
@JoshuaVSherman, a few questions: 

> [error] failed to retrieve test file list. TestExplorer might show incomplete test items

Please copy/paste the terminal output where you saw the error above. I am looking for the top where it showed auto config info and what command it issued for the run. Also please check the console log and see if there is any error from the extension.

This might be obvious, but just want to confirm that you guys did try to `Reload Window` before reinstalling the extension and that did not fix the problem, correct? 

The error message `ERROR: Invalid Option: --testLocationInResults"` implied something might be wrong with the command line... what is it? If you have a problem finding it from the output terminal, then please try turning on the debug mode: https://github.com/jest-community/vscode-jest#how-to-see-more-debug-info-self-diagnosis

**Comment by xtina** [comment]
I am on Mac, intel chip running OSX 13.1
`Reload Window` did not work post uninstall/pre-reinstall

```
Jest (blah)

[info] auto config:

found:
  rootPath: /Users/blah/blah
  jestCommandLine: "/Users/blah/blah/node_modules/.bin/react-scripts"

Unknown script "--testLocationInResults".
Perhaps you need to update react-scripts?
See: https://facebook.github.io/create-react-app/docs/updating-to-new-releases
```

Turning on debug and opening devtools didn't reveal anything.

**Comment by connectdotz** [comment]
@xtina great, we are getting more info now. 

A few more questions: What version of the react you are running? How do you run test from the terminal? Such as `yarn test`. Do you have a test script in `package.json`? What does it look like? If you set `jest.jestCommandLine` to the way you run test from the terminal, does it work? Do you have a sample repo we can try to reproduce this issue?

**Comment by JoshuaVSherman** [comment]
here is the console with error from vscode (when I run `npm test` from terminal there is no problem) 
```
[Extension Host] [JaMmusic/JestTestProvider] executing profile: "run" for orta.vscode-jest:JaMmusic...
console.ts:137 [Extension Host] [JaMmusic/ProcessSessionManager] scheduling jest process: all-tests
console.ts:137 [Extension Host] spawning process with command=npm test -- --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_jammusic_1000_2.json --no-coverage --reporters default --reporters "/home/joshua/.vscode/extensions/orta.vscode-jest-5.2.2/out/reporter.js" --colors --watchAll=false options: {cwd: '/home/joshua/WebJamApps/JaMmusic', env: {…}, shell: true, detached: true}
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/97dec172d3256f8ca4bfb2143f3f76b503ca0534/core/vs/editor/common/services/editorSimpleWorker.nls.js.map: Load canceled due to load timeout
console.ts:137 [Extension Host] [JaMmusic/ProcessSessionManager] scheduling jest process: watch-tests
console.ts:137 [Extension Host] spawning process with command=npm test -- --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_jammusic_1000.json --watch --no-coverage --reporters default --reporters "/home/joshua/.vscode/extensions/orta.vscode-jest-5.2.2/out/reporter.js" --colors options: {cwd: '/home/joshua/WebJamApps/JaMmusic', env: {…}, shell: true, detached: true}
console.ts:137 [Extension Host] [JaMmusic/ProcessSessionManager] scheduling jest process: list-test-files
console.ts:137 [Extension Host] spawning process with command=npm test -- --listTests --json --watchAll=false options: {cwd: '/home/joshua/WebJamApps/JaMmusic', env: {…}, shell: true, detached: true}
console.ts:137 [Extension Host] [JaMmusic/JestExt] found undefined testFiles
log.ts:316   ERR [Extension Host] [JaMmusic/JestExt] failed to retrieve test file list. TestExplorer might show incomplete test items PASS test/containers/Music/Gigs/gigs.utils.spec.tsx (9.754 s)
  gigs.utils
    ✓ makeVenueValue when Our Past Performances (4 ms)
    ✓ properly sets the order for gigs (1 ms)
    ✓ properly sets the order for gigs when we have many future gigs (2 ms)
    ✓ makeVenue
    ✓ deleteGig successful (40 ms)
    ✓ deleteGig returns false
    ✓ deleteGig catches error (24 ms)
    ✓ updateGig successful (2 ms)
    ✓ updateGig catches error (3 ms)
    ✓ createGig successful (2 ms)
    ✓ createGig catches error (4 ms)
    ✓ checkUpdateDisabled
    ✓ checkNewDisabled (1 ms)
    ✓ clickToEdit when isAdmin
    ✓ clickToEdit when not isAdmin

PASS test/containers/Music/Gigs/index.spec.tsx (8.269 s)
  Gigs
    ✓ renders correctly when not isAdmin (27 ms)
    ✓ renders GigsDiv when isAdmin and handles onRowClick (24 ms)
    ✓ renders ShowCreateGigButton and handles click (2 ms)
    ✓ renders the location cell with city, state
    ✓ renders the location cell with location
    ✓ renders the location cell when undefined
    ✓ makeTickets (3 ms)
    ✓ makeTickets defaults to Free (1 ms)
    ✓ makeDateValue (16 ms)
    ✓ makeDateValue when null
    ✓ makeTimeValue (1 ms)
    ✓ makeTimeValue when null

PASS test/containers/Music/index.spec.tsx (7.293 s)
  /music
    ✓ renders the component (37 ms)
    ✓ renders and runs useEffect (245 ms)
    ✓ renders ClickToListen and handles click when joshandmariamusic.com (3 ms)
    ✓ renders ClickToListen and handles click when web-jam.com (41 ms)
    ✓ renders ClickToListen and handles click when undefined appName (3 ms)
    ✓ checkIsAdmin when true (2 ms)

PASS test/containers/Music/Gigs/EditGigDialog.spec.tsx
  EditGigDialog
    ✓ renders and handles events (21 ms)
    ✓ renders ButtonSection and handles clicks (1 ms)
    ✓ renders the VenueEditor and handles event (4 ms)
    ✓ renders EditText and handles onChange (1 ms)

PASS test/App/AppTemplate/SideMenuItem.spec.tsx
  SideMenuItem
    ✓ is defined (3 ms)
    ✓ renders MakeLink for /music (15 ms)
    ✓ returns MakeLink for /music when Web Jam LLC (6 ms)
    ✓ continueMenuItem returns googleLogout
    ✓ checkIsAllowed return false if item requires auth and userType is not allowed (1 ms)

PASS test/App/AppTemplate/GoogleButtons/utils.spec.tsx
  GoogleButtons/utils
    ✓ responseGoogleLogout (4 ms)
    ✓ makeState (1 ms)

PASS test/App/AppTemplate/GoogleButtons/index.spec.tsx
  GoogleButtons
    ✓ is defined (3 ms)
    ✓ renders GoogleLogin button and runs events (12 ms)
    ✓ runs loginConfig onSuccess and onError (5 ms)
    ✓ renders GoogleLogout button and handles click (1 ms)

PASS test/containers/Music/Gigs/CreateGigDialog.spec.tsx
  CreateGigDialog
    ✓ renders and handles events (90 ms)

PASS test/redux/socketReducer.spec.ts
  socket reducer
    ✓ should return the initial state (4 ms)
    ✓ changes color to white
    ✓ changes color to green
    ✓ handles SCC (1 ms)
    ✓ handles NUM_USERS

PASS test/providers/fetchSongs.spec.tsx
  fetchSongs
    ✓ getSongs returns default (9 ms)
    ✓ getSongs returns songs (1 ms)
    ✓ getSongs returns empty array (7 ms)
    ✓ getSongs does not fetch (1 ms)

PASS test/App/PageHost.spec.tsx
  PageHost
    ✓ renders correctly (23 ms)
    ✓ makeDrawerClass
    ✓ handleEscapePress (2 ms)
    ✓ handleKeyMenu


console.ts:137 [Extension Host] [JaMmusic/JestExt] failed to retrieve test file list. TestExplorer might show incomplete test items PASS test/containers/Music/Gigs/gigs.utils.spec.tsx (9.754 s)
  gigs.utils
    ✓ makeVenueValue when Our Past Performances (4 ms)
    ✓ properly sets the order for gigs (1 ms)
    ✓ properly sets the order for gigs when we have many future gigs (2 ms)
    ✓ makeVenue
    ✓ deleteGig successful (40 ms)
    ✓ deleteGig returns false
    ✓ deleteGig catches error (24 ms)
    ✓ updateGig successful (2 ms)
    ✓ updateGig catches error (3 ms)
    ✓ createGig successful (2 ms)
    ✓ createGig catches error (4 ms)
    ✓ checkUpdateDisabled
    ✓ checkNewDisabled (1 ms)
    ✓ clickToEdit when isAdmin
    ✓ clickToEdit when not isAdmin

PASS test/containers/Music/Gigs/index.spec.tsx (8.269 s)
  Gigs
    ✓ renders correctly when not isAdmin (27 ms)
    ✓ renders GigsDiv when isAdmin and handles onRowClick (24 ms)
    ✓ renders ShowCreateGigButton and handles click (2 ms)
    ✓ renders the location cell with city, state
    ✓ renders the location cell with location
    ✓ renders the location cell when undefined
    ✓ makeTickets (3 ms)
    ✓ makeTickets defaults to Free (1 ms)
    ✓ makeDateValue (16 ms)
    ✓ makeDateValue when null
    ✓ makeTimeValue (1 ms)
    ✓ makeTimeValue when null

PASS test/containers/Music/index.spec.tsx (7.293 s)
  /music
    ✓ renders the component (37 ms)
    ✓ renders and runs useEffect (245 ms)
    ✓ renders ClickToListen and handles click when joshandmariamusic.com (3 ms)
    ✓ renders ClickToListen and handles click when web-jam.com (41 ms)
    ✓ renders ClickToListen and handles click when undefined appName (3 ms)
    ✓ checkIsAdmin when true (2 ms)

PASS test/containers/Music/Gigs/EditGigDialog.spec.tsx
  EditGigDialog
    ✓ renders and handles events (21 ms)
    ✓ renders ButtonSection and handles clicks (1 ms)
    ✓ renders the VenueEditor and handles event (4 ms)
    ✓ renders EditText and handles onChange (1 ms)

PASS test/App/AppTemplate/SideMenuItem.spec.tsx
  SideMenuItem
    ✓ is defined (3 ms)
    ✓ renders MakeLink for /music (15 ms)
    ✓ returns MakeLink for /music when Web Jam LLC (6 ms)
    ✓ continueMenuItem returns googleLogout
    ✓ checkIsAllowed return false if item requires auth and userType is not allowed (1 ms)

PASS test/App/AppTemplate/GoogleButtons/utils.spec.tsx
  GoogleButtons/utils
    ✓ responseGoogleLogout (4 ms)
    ✓ makeState (1 ms)

PASS test/App/AppTemplate/GoogleButtons/index.spec.tsx
  GoogleButtons
    ✓ is defined (3 ms)
    ✓ renders GoogleLogin button and runs events (12 ms)
    ✓ runs loginConfig onSuccess and onError (5 ms)
    ✓ renders GoogleLogout button and handles click (1 ms)

PASS test/containers/Music/Gigs/CreateGigDialog.spec.tsx
  CreateGigDialog
    ✓ renders and handles events (90 ms)

PASS test/redux/socketReducer.spec.ts
  socket reducer
    ✓ should return the initial state (4 ms)
    ✓ changes color to white
    ✓ changes color to green
    ✓ handles SCC (1 ms)
    ✓ handles NUM_USERS

PASS test/providers/fetchSongs.spec.tsx
  fetchSongs
    ✓ getSongs returns default (9 ms)
    ✓ getSongs returns songs (1 ms)
    ✓ getSongs returns empty array (7 ms)
    ✓ getSongs does not fetch (1 ms)

PASS test/App/PageHost.spec.tsx
  PageHost
    ✓ renders correctly (23 ms)
    ✓ makeDrawerClass
    ✓ handleEscapePress (2 ms)
    ✓ handleKeyMenu


E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
fire @ ipc.net.ts:646
y @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
k @ ipc.net.ts:87
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.js:2743 [uncaught exception]: TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
s @ workbench.js:2743
(anonymous) @ workbench.js:2534
emit @ node:events:526
window.onerror @ node:electron/js2c/renderer_init:85
L.globals.onerror @ errorTelemetry.ts:20
workbench.js:2746 TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
    at p.Q (listView.ts:494:9)
    at p.splice (listView.ts:478:16)
    at splice.ts:17:25
    at Array.forEach (<anonymous>)
    at t.splice (splice.ts:17:10)
    at listWidget.ts:1442:36
    at v.bufferEvents (event.ts:1197:13)
    at G.splice (listWidget.ts:1442:10)
    at G.splice (abstractTree.ts:1321:9)
    at C.refilter (indexTreeModel.ts:493:10)
    at R.refilter (objectTreeModel.ts:248:10)
    at Q.refilter (abstractTree.ts:1718:10)
    at ce.S (testingExplorerView.ts:808:13)
    at N.a (testingExplorerView.ts:793:53)
    at N.h (async.ts:886:8)
    at N.g (async.ts:881:9)
s @ workbench.js:2746
(anonymous) @ workbench.js:2534
emit @ node:events:526
window.onerror @ node:electron/js2c/renderer_init:85
L.globals.onerror @ errorTelemetry.ts:20
listView.ts:494 Uncaught TypeError: Cannot read properties of undefined (reading 'dragStartDisposable')
    at p.Q (listView.ts:494:9)
    at p.splice (listView.ts:478:16)
    at splice.ts:17:25
    at Array.forEach (<anonymous>)
    at t.splice (splice.ts:17:10)
    at listWidget.ts:1442:36
    at v.bufferEvents (event.ts:1197:13)
    at G.splice (listWidget.ts:1442:10)
    at G.splice (abstractTree.ts:1321:9)
    at C.refilter (indexTreeModel.ts:493:10)
    at R.refilter (objectTreeModel.ts:248:10)
    at Q.refilter (abstractTree.ts:1718:10)
    at ce.S (testingExplorerView.ts:808:13)
    at N.a (testingExplorerView.ts:793:53)
    at N.h (async.ts:886:8)
    at N.g (async.ts:881:9)
Q @ listView.ts:494
splice @ listView.ts:478
(anonymous) @ splice.ts:17
splice @ splice.ts:17
(anonymous) @ listWidget.ts:1442
bufferEvents @ event.ts:1197
splice @ listWidget.ts:1442
splice @ abstractTree.ts:1321
refilter @ indexTreeModel.ts:493
refilter @ objectTreeModel.ts:248
refilter @ abstractTree.ts:1718
S @ testingExplorerView.ts:808
(anonymous) @ testingExplorerView.ts:793
h @ async.ts:886
g @ async.ts:881
setTimeout (async)
schedule @ async.ts:860
(anonymous) @ testingExplorerView.ts:796
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
v @ hierarchalByLocation.ts:192
(anonymous) @ hierarchalByLocation.ts:70
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
publishDiff @ testServiceImpl.ts:237
(anonymous) @ testServiceImpl.ts:309
(anonymous) @ lifecycle.ts:195
(anonymous) @ functional.ts:17
c @ lifecycle.ts:150
clear @ lifecycle.ts:250
dispose @ lifecycle.ts:231
c @ lifecycle.ts:150
clear @ lifecycle.ts:250
dispose @ lifecycle.ts:231
$unregisterTestController @ mainThreadTesting.ts:214
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
fire @ ipc.net.ts:646
y @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
k @ ipc.net.ts:87
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
Show 28 more frames
console.ts:137 [Extension Host] [JaMmusic/RunTestListener] Jest process "watch-tests" ended unexpectedly
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
fire @ ipc.net.ts:646
y @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
k @ ipc.net.ts:87
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
notificationsAlerts.ts:42 Jest process "watch-tests" ended unexpectedly
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
addNotification @ notifications.ts:204
notify @ notificationService.ts:175
(anonymous) @ mainThreadMessageService.ts:77
d @ mainThreadMessageService.ts:42
$showMessage @ mainThreadMessageService.ts:36
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
fire @ ipc.net.ts:646
y @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
k @ ipc.net.ts:87
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
Show 2 more frames
console.ts:137 [Extension Host] [JaMmusic/ListTestFileListener] no test file is found
console.ts:137 [Extension Host] [JaMmusic/JestExt] found 0 testFiles
```

**Comment by xtina** [comment]
> Ok, I see the problem now. For react, it usually picks up the test script from `package.json`, where it looks like `"test": "react-scripts test --env=jsdom"` For some reason it didn't find it in your env... 🤔 And the auto config did not append the "test" argument thus `react-scripts` not able to recognize we are asking it to run tests.
> 
> The workaround is to set `jest.jestCommandLine` to the command you run tests from the terminal for now. But I would really like to find out why the auto-config did not find the test script from your package.json... Is it in the folder's rootPath? Is there a "test" in the scripts section and what is it?

@connectdotz Thank you for the workaround. I do have a `test` in my package.json and it is `"test": "DEBUG_PRINT_LIMIT=100000000 TZ=America/New_York craco test --testPathIgnorePatterns=\"ignoreMe.test.ts|<rootDir>/src/ui-library/|<rootDir>/node_modules/\"",`. 

Is the problem that i'm using `craco test`?

**Comment by connectdotz** [comment]
@xtina, Thanks for the info, now I think I fully understand how to fix your issue, and maybe other similar ones as well.

> Is the problem that i'm using craco test?

Yes. we look for patterns including react/react-native scripts. If none is found, we will not use the script and favor the binary instead, which is wrong in this case. I will patch this bug so that for react/react-native workspaces, if there a test script, we should just use it, even if no recognized patterns are found.

**Comment by connectdotz** [comment]
@JoshuaVSherman,

Your use case appears to be different from the others. It seems you were able to run the test but failed to get the test file list for some reason. Did your workspace work in 4.6 but failed in 5.x? (if it never did work, then please consider opening a new issue) Can you run this command from the terminal and show us the first few lines of the output so I can see if there is any parsing error for the test file list:
`npm test -- --listTests --json --watchAll=false`
Also, what does your test script (in package.json) look like?

**Comment by JoshuaVSherman** [comment]
Yes it was working until I did an update and I did not change anything else
other than also updating my jest version.  It also fails for my daughter on
her laptop and on two different projects

**Comment by connectdotz** [comment]
@JoshuaVSherman, thanks for the clarification. Some follow up questions:

1. the test command appeared to be correct, as it did run the tests (from your log). Other than the list-file error message, is there anything else that appears not working? The test status icons should reflect the test results, and you should still see the test explorer populated, etc.
2. regarding the test file error, please run the command I listed above in your terminal, or provide a sample repo so that I can diagnose further.
